import { paths } from "../types/aaa-api.ts";
type CategoryType = paths["/categories/{id}"]["get"]["responses"]["200"]["content"]["application/json"];
const arxivCategories: CategoryType[] = [
    {
        "id": "acc-phys.",
        "archive": "acc-phys",
        "subject_class": "",
        "definitive": true,
        "active": false,
        "category_name": "Accelerator Physics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "acc-phys"
    },
    {
        "id": "adap-org.",
        "archive": "adap-org",
        "subject_class": "",
        "definitive": true,
        "active": false,
        "category_name": "Adaptation, Noise, and Self-Organizing Systems",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "adap-org"
    },
    {
        "id": "alg-geom.",
        "archive": "alg-geom",
        "subject_class": "",
        "definitive": true,
        "active": false,
        "category_name": "Algebraic Geometry",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "alg-geom"
    },
    {
        "id": "ao-sci.",
        "archive": "ao-sci",
        "subject_class": "",
        "definitive": true,
        "active": false,
        "category_name": "Atmospheric-Oceanic Sciences",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "ao-sci"
    },
    {
        "id": "astro-ph.",
        "archive": "astro-ph",
        "subject_class": "",
        "definitive": true,
        "active": true,
        "category_name": "Astrophysics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "astro-ph"
    },
    {
        "id": "astro-ph.CO",
        "archive": "astro-ph",
        "subject_class": "CO",
        "definitive": true,
        "active": true,
        "category_name": "Cosmology and Nongalactic Astrophysics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "astro-ph"
    },
    {
        "id": "astro-ph.EP",
        "archive": "astro-ph",
        "subject_class": "EP",
        "definitive": true,
        "active": true,
        "category_name": "Earth and Planetary Astrophysics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "astro-ph"
    },
    {
        "id": "astro-ph.GA",
        "archive": "astro-ph",
        "subject_class": "GA",
        "definitive": true,
        "active": true,
        "category_name": "Astrophysics of Galaxies",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "astro-ph"
    },
    {
        "id": "astro-ph.HE",
        "archive": "astro-ph",
        "subject_class": "HE",
        "definitive": true,
        "active": true,
        "category_name": "High Energy Astrophysical Phenomena",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "astro-ph"
    },
    {
        "id": "astro-ph.IM",
        "archive": "astro-ph",
        "subject_class": "IM",
        "definitive": true,
        "active": true,
        "category_name": "Instrumentation and Methods for Astrophysics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "astro-ph"
    },
    {
        "id": "astro-ph.SR",
        "archive": "astro-ph",
        "subject_class": "SR",
        "definitive": true,
        "active": true,
        "category_name": "Solar and Stellar Astrophysics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "astro-ph"
    },
    {
        "id": "atom-ph.",
        "archive": "atom-ph",
        "subject_class": "",
        "definitive": true,
        "active": false,
        "category_name": "Atomic, Molecular and Optical Physics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "atom-ph"
    },
    {
        "id": "bayes-an.",
        "archive": "bayes-an",
        "subject_class": "",
        "definitive": true,
        "active": false,
        "category_name": "Bayesian Analysis",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "bayes-an"
    },
    {
        "id": "chao-dyn.",
        "archive": "chao-dyn",
        "subject_class": "",
        "definitive": true,
        "active": false,
        "category_name": "Chaotic Dynamics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "chao-dyn"
    },
    {
        "id": "chem-ph.",
        "archive": "chem-ph",
        "subject_class": "",
        "definitive": true,
        "active": false,
        "category_name": "Chemical Physics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "chem-ph"
    },
    {
        "id": "cmp-lg.",
        "archive": "cmp-lg",
        "subject_class": "",
        "definitive": true,
        "active": false,
        "category_name": "Computation and Language",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cmp-lg"
    },
    {
        "id": "comp-gas.",
        "archive": "comp-gas",
        "subject_class": "",
        "definitive": true,
        "active": false,
        "category_name": "Cellular Automata and Lattice Gases",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "comp-gas"
    },
    {
        "id": "cond-mat.",
        "archive": "cond-mat",
        "subject_class": "",
        "definitive": false,
        "active": true,
        "category_name": "Condensed Matter",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cond-mat"
    },
    {
        "id": "cond-mat.dis-nn",
        "archive": "cond-mat",
        "subject_class": "dis-nn",
        "definitive": true,
        "active": true,
        "category_name": "Disordered Systems and Neural Networks",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cond-mat"
    },
    {
        "id": "cond-mat.mes-hall",
        "archive": "cond-mat",
        "subject_class": "mes-hall",
        "definitive": true,
        "active": true,
        "category_name": "Mesoscale and Nanoscale Physics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cond-mat"
    },
    {
        "id": "cond-mat.mtrl-sci",
        "archive": "cond-mat",
        "subject_class": "mtrl-sci",
        "definitive": true,
        "active": true,
        "category_name": "Materials Science",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cond-mat"
    },
    {
        "id": "cond-mat.none",
        "archive": "cond-mat",
        "subject_class": "none",
        "definitive": true,
        "active": false,
        "category_name": "Condensed Matter",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cond-mat"
    },
    {
        "id": "cond-mat.other",
        "archive": "cond-mat",
        "subject_class": "other",
        "definitive": true,
        "active": true,
        "category_name": "Other Condensed Matter",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cond-mat"
    },
    {
        "id": "cond-mat.quant-gas",
        "archive": "cond-mat",
        "subject_class": "quant-gas",
        "definitive": true,
        "active": true,
        "category_name": "Quantum Gases",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cond-mat"
    },
    {
        "id": "cond-mat.soft",
        "archive": "cond-mat",
        "subject_class": "soft",
        "definitive": true,
        "active": true,
        "category_name": "Soft Condensed Matter",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cond-mat"
    },
    {
        "id": "cond-mat.stat-mech",
        "archive": "cond-mat",
        "subject_class": "stat-mech",
        "definitive": true,
        "active": true,
        "category_name": "Statistical Mechanics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cond-mat"
    },
    {
        "id": "cond-mat.str-el",
        "archive": "cond-mat",
        "subject_class": "str-el",
        "definitive": true,
        "active": true,
        "category_name": "Strongly Correlated Electrons",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cond-mat"
    },
    {
        "id": "cond-mat.supr-con",
        "archive": "cond-mat",
        "subject_class": "supr-con",
        "definitive": true,
        "active": true,
        "category_name": "Superconductivity",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cond-mat"
    },
    {
        "id": "cs.",
        "archive": "cs",
        "subject_class": "",
        "definitive": false,
        "active": true,
        "category_name": "Computer Science",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cs"
    },
    {
        "id": "cs.AI",
        "archive": "cs",
        "subject_class": "AI",
        "definitive": true,
        "active": true,
        "category_name": "Artificial Intelligence",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cs"
    },
    {
        "id": "cs.AR",
        "archive": "cs",
        "subject_class": "AR",
        "definitive": true,
        "active": true,
        "category_name": "Hardware Architecture",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cs"
    },
    {
        "id": "cs.CC",
        "archive": "cs",
        "subject_class": "CC",
        "definitive": true,
        "active": true,
        "category_name": "Computational Complexity",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cs"
    },
    {
        "id": "cs.CE",
        "archive": "cs",
        "subject_class": "CE",
        "definitive": true,
        "active": true,
        "category_name": "Computational Engineering, Finance, and Science",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cs"
    },
    {
        "id": "cs.CG",
        "archive": "cs",
        "subject_class": "CG",
        "definitive": true,
        "active": true,
        "category_name": "Computational Geometry",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cs"
    },
    {
        "id": "cs.CL",
        "archive": "cs",
        "subject_class": "CL",
        "definitive": true,
        "active": true,
        "category_name": "Computation and Language",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cs"
    },
    {
        "id": "cs.CR",
        "archive": "cs",
        "subject_class": "CR",
        "definitive": true,
        "active": true,
        "category_name": "Cryptography and Security",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cs"
    },
    {
        "id": "cs.CV",
        "archive": "cs",
        "subject_class": "CV",
        "definitive": true,
        "active": true,
        "category_name": "Computer Vision and Pattern Recognition",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cs"
    },
    {
        "id": "cs.CY",
        "archive": "cs",
        "subject_class": "CY",
        "definitive": true,
        "active": true,
        "category_name": "Computers and Society",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cs"
    },
    {
        "id": "cs.DB",
        "archive": "cs",
        "subject_class": "DB",
        "definitive": true,
        "active": true,
        "category_name": "Databases",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cs"
    },
    {
        "id": "cs.DC",
        "archive": "cs",
        "subject_class": "DC",
        "definitive": true,
        "active": true,
        "category_name": "Distributed, Parallel, and Cluster Computing",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cs"
    },
    {
        "id": "cs.DL",
        "archive": "cs",
        "subject_class": "DL",
        "definitive": true,
        "active": true,
        "category_name": "Digital Libraries",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cs"
    },
    {
        "id": "cs.DM",
        "archive": "cs",
        "subject_class": "DM",
        "definitive": true,
        "active": true,
        "category_name": "Discrete Mathematics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cs"
    },
    {
        "id": "cs.DS",
        "archive": "cs",
        "subject_class": "DS",
        "definitive": true,
        "active": true,
        "category_name": "Data Structures and Algorithms",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cs"
    },
    {
        "id": "cs.ET",
        "archive": "cs",
        "subject_class": "ET",
        "definitive": true,
        "active": true,
        "category_name": "Emerging Technologies",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cs"
    },
    {
        "id": "cs.FL",
        "archive": "cs",
        "subject_class": "FL",
        "definitive": true,
        "active": true,
        "category_name": "Formal Languages and Automata Theory",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cs"
    },
    {
        "id": "cs.GL",
        "archive": "cs",
        "subject_class": "GL",
        "definitive": true,
        "active": true,
        "category_name": "General Literature",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cs"
    },
    {
        "id": "cs.GR",
        "archive": "cs",
        "subject_class": "GR",
        "definitive": true,
        "active": true,
        "category_name": "Graphics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cs"
    },
    {
        "id": "cs.GT",
        "archive": "cs",
        "subject_class": "GT",
        "definitive": true,
        "active": true,
        "category_name": "Computer Science and Game Theory",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cs"
    },
    {
        "id": "cs.HC",
        "archive": "cs",
        "subject_class": "HC",
        "definitive": true,
        "active": true,
        "category_name": "Human-Computer Interaction",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cs"
    },
    {
        "id": "cs.IR",
        "archive": "cs",
        "subject_class": "IR",
        "definitive": true,
        "active": true,
        "category_name": "Information Retrieval",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cs"
    },
    {
        "id": "cs.IT",
        "archive": "cs",
        "subject_class": "IT",
        "definitive": true,
        "active": true,
        "category_name": "Information Theory",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cs"
    },
    {
        "id": "cs.LG",
        "archive": "cs",
        "subject_class": "LG",
        "definitive": true,
        "active": true,
        "category_name": "Learning",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cs"
    },
    {
        "id": "cs.LO",
        "archive": "cs",
        "subject_class": "LO",
        "definitive": true,
        "active": true,
        "category_name": "Logic in Computer Science",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cs"
    },
    {
        "id": "cs.MA",
        "archive": "cs",
        "subject_class": "MA",
        "definitive": true,
        "active": true,
        "category_name": "Multiagent Systems",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cs"
    },
    {
        "id": "cs.MM",
        "archive": "cs",
        "subject_class": "MM",
        "definitive": true,
        "active": true,
        "category_name": "Multimedia",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cs"
    },
    {
        "id": "cs.MS",
        "archive": "cs",
        "subject_class": "MS",
        "definitive": true,
        "active": true,
        "category_name": "Mathematical Software",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cs"
    },
    {
        "id": "cs.NA",
        "archive": "cs",
        "subject_class": "NA",
        "definitive": true,
        "active": true,
        "category_name": "Numerical Analysis",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cs"
    },
    {
        "id": "cs.NE",
        "archive": "cs",
        "subject_class": "NE",
        "definitive": true,
        "active": true,
        "category_name": "Neural and Evolutionary Computing",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cs"
    },
    {
        "id": "cs.NI",
        "archive": "cs",
        "subject_class": "NI",
        "definitive": true,
        "active": true,
        "category_name": "Networking and Internet Architecture",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cs"
    },
    {
        "id": "cs.OH",
        "archive": "cs",
        "subject_class": "OH",
        "definitive": true,
        "active": true,
        "category_name": "Other Computer Science",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cs"
    },
    {
        "id": "cs.OS",
        "archive": "cs",
        "subject_class": "OS",
        "definitive": true,
        "active": true,
        "category_name": "Operating Systems",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cs"
    },
    {
        "id": "cs.PF",
        "archive": "cs",
        "subject_class": "PF",
        "definitive": true,
        "active": true,
        "category_name": "Performance",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cs"
    },
    {
        "id": "cs.PL",
        "archive": "cs",
        "subject_class": "PL",
        "definitive": true,
        "active": true,
        "category_name": "Programming Languages",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cs"
    },
    {
        "id": "cs.RO",
        "archive": "cs",
        "subject_class": "RO",
        "definitive": true,
        "active": true,
        "category_name": "Robotics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cs"
    },
    {
        "id": "cs.SC",
        "archive": "cs",
        "subject_class": "SC",
        "definitive": true,
        "active": true,
        "category_name": "Symbolic Computation",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cs"
    },
    {
        "id": "cs.SD",
        "archive": "cs",
        "subject_class": "SD",
        "definitive": true,
        "active": true,
        "category_name": "Sound",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cs"
    },
    {
        "id": "cs.SE",
        "archive": "cs",
        "subject_class": "SE",
        "definitive": true,
        "active": true,
        "category_name": "Software Engineering",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cs"
    },
    {
        "id": "cs.SI",
        "archive": "cs",
        "subject_class": "SI",
        "definitive": true,
        "active": true,
        "category_name": "Social and Information Networks",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cs"
    },
    {
        "id": "cs.SY",
        "archive": "cs",
        "subject_class": "SY",
        "definitive": true,
        "active": true,
        "category_name": "Systems and Control",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "cs"
    },
    {
        "id": "dg-ga.",
        "archive": "dg-ga",
        "subject_class": "",
        "definitive": true,
        "active": false,
        "category_name": "Differential Geometry",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "dg-ga"
    },
    {
        "id": "econ.",
        "archive": "econ",
        "subject_class": "",
        "definitive": false,
        "active": true,
        "category_name": "Economics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "econ"
    },
    {
        "id": "econ.EM",
        "archive": "econ",
        "subject_class": "EM",
        "definitive": true,
        "active": true,
        "category_name": "Econometrics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "econ"
    },
    {
        "id": "econ.GN",
        "archive": "econ",
        "subject_class": "GN",
        "definitive": true,
        "active": true,
        "category_name": "General Economics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "econ"
    },
    {
        "id": "econ.TH",
        "archive": "econ",
        "subject_class": "TH",
        "definitive": true,
        "active": true,
        "category_name": "Theoretical Economics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "econ"
    },
    {
        "id": "eess.",
        "archive": "eess",
        "subject_class": "",
        "definitive": false,
        "active": true,
        "category_name": "Electrical Engineering and Systems Science",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "eess"
    },
    {
        "id": "eess.AS",
        "archive": "eess",
        "subject_class": "AS",
        "definitive": true,
        "active": true,
        "category_name": "Audio and Speech Processing",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "eess"
    },
    {
        "id": "eess.IV",
        "archive": "eess",
        "subject_class": "IV",
        "definitive": true,
        "active": true,
        "category_name": "Image and Video Processing",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "eess"
    },
    {
        "id": "eess.SP",
        "archive": "eess",
        "subject_class": "SP",
        "definitive": true,
        "active": true,
        "category_name": "Signal Processing",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "eess"
    },
    {
        "id": "eess.SY",
        "archive": "eess",
        "subject_class": "SY",
        "definitive": true,
        "active": true,
        "category_name": "Systems and Control",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "eess"
    },
    {
        "id": "funct-an.",
        "archive": "funct-an",
        "subject_class": "",
        "definitive": true,
        "active": false,
        "category_name": "Functional Analysis",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "funct-an"
    },
    {
        "id": "gr-qc.",
        "archive": "gr-qc",
        "subject_class": "",
        "definitive": true,
        "active": true,
        "category_name": "General Relativity and Quantum Cosmology",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "gr-qc"
    },
    {
        "id": "hep-ex.",
        "archive": "hep-ex",
        "subject_class": "",
        "definitive": true,
        "active": true,
        "category_name": "High Energy Physics - Experiment",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "hep-ex"
    },
    {
        "id": "hep-lat.",
        "archive": "hep-lat",
        "subject_class": "",
        "definitive": true,
        "active": true,
        "category_name": "High Energy Physics - Lattice",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "hep-lat"
    },
    {
        "id": "hep-ph.",
        "archive": "hep-ph",
        "subject_class": "",
        "definitive": true,
        "active": true,
        "category_name": "High Energy Physics - Phenomenology",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "hep-ph"
    },
    {
        "id": "hep-th.",
        "archive": "hep-th",
        "subject_class": "",
        "definitive": true,
        "active": true,
        "category_name": "High Energy Physics - Theory",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "hep-th"
    },
    {
        "id": "math.",
        "archive": "math",
        "subject_class": "",
        "definitive": false,
        "active": true,
        "category_name": "Mathematics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "math"
    },
    {
        "id": "math.AC",
        "archive": "math",
        "subject_class": "AC",
        "definitive": true,
        "active": true,
        "category_name": "Commutative Algebra",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "math"
    },
    {
        "id": "math.AG",
        "archive": "math",
        "subject_class": "AG",
        "definitive": true,
        "active": true,
        "category_name": "Algebraic Geometry",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "math"
    },
    {
        "id": "math.AP",
        "archive": "math",
        "subject_class": "AP",
        "definitive": true,
        "active": true,
        "category_name": "Analysis of PDEs",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "math"
    },
    {
        "id": "math.AT",
        "archive": "math",
        "subject_class": "AT",
        "definitive": true,
        "active": true,
        "category_name": "Algebraic Topology",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "math"
    },
    {
        "id": "math.CA",
        "archive": "math",
        "subject_class": "CA",
        "definitive": true,
        "active": true,
        "category_name": "Classical Analysis and ODEs",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "math"
    },
    {
        "id": "math.CO",
        "archive": "math",
        "subject_class": "CO",
        "definitive": true,
        "active": true,
        "category_name": "Combinatorics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "math"
    },
    {
        "id": "math.CT",
        "archive": "math",
        "subject_class": "CT",
        "definitive": true,
        "active": true,
        "category_name": "Category Theory",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "math"
    },
    {
        "id": "math.CV",
        "archive": "math",
        "subject_class": "CV",
        "definitive": true,
        "active": true,
        "category_name": "Complex Variables",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "math"
    },
    {
        "id": "math.DG",
        "archive": "math",
        "subject_class": "DG",
        "definitive": true,
        "active": true,
        "category_name": "Differential Geometry",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "math"
    },
    {
        "id": "math.DS",
        "archive": "math",
        "subject_class": "DS",
        "definitive": true,
        "active": true,
        "category_name": "Dynamical Systems",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "math"
    },
    {
        "id": "math.FA",
        "archive": "math",
        "subject_class": "FA",
        "definitive": true,
        "active": true,
        "category_name": "Functional Analysis",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "math"
    },
    {
        "id": "math.GM",
        "archive": "math",
        "subject_class": "GM",
        "definitive": true,
        "active": true,
        "category_name": "General Mathematics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "math.GM"
    },
    {
        "id": "math.GN",
        "archive": "math",
        "subject_class": "GN",
        "definitive": true,
        "active": true,
        "category_name": "General Topology",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "math"
    },
    {
        "id": "math.GR",
        "archive": "math",
        "subject_class": "GR",
        "definitive": true,
        "active": true,
        "category_name": "Group Theory",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "math"
    },
    {
        "id": "math.GT",
        "archive": "math",
        "subject_class": "GT",
        "definitive": true,
        "active": true,
        "category_name": "Geometric Topology",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "math"
    },
    {
        "id": "math.HO",
        "archive": "math",
        "subject_class": "HO",
        "definitive": true,
        "active": true,
        "category_name": "History and Overview",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "math"
    },
    {
        "id": "math.IT",
        "archive": "math",
        "subject_class": "IT",
        "definitive": true,
        "active": true,
        "category_name": "Information Theory",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "math"
    },
    {
        "id": "math.KT",
        "archive": "math",
        "subject_class": "KT",
        "definitive": true,
        "active": true,
        "category_name": "K-Theory and Homology",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "math"
    },
    {
        "id": "math.LO",
        "archive": "math",
        "subject_class": "LO",
        "definitive": true,
        "active": true,
        "category_name": "Logic",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "math"
    },
    {
        "id": "math.MG",
        "archive": "math",
        "subject_class": "MG",
        "definitive": true,
        "active": true,
        "category_name": "Metric Geometry",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "math"
    },
    {
        "id": "math.MP",
        "archive": "math",
        "subject_class": "MP",
        "definitive": true,
        "active": true,
        "category_name": "Mathematical Physics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "math"
    },
    {
        "id": "math.NA",
        "archive": "math",
        "subject_class": "NA",
        "definitive": true,
        "active": true,
        "category_name": "Numerical Analysis",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "math"
    },
    {
        "id": "math.NT",
        "archive": "math",
        "subject_class": "NT",
        "definitive": true,
        "active": true,
        "category_name": "Number Theory",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "math"
    },
    {
        "id": "math.OA",
        "archive": "math",
        "subject_class": "OA",
        "definitive": true,
        "active": true,
        "category_name": "Operator Algebras",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "math"
    },
    {
        "id": "math.OC",
        "archive": "math",
        "subject_class": "OC",
        "definitive": true,
        "active": true,
        "category_name": "Optimization and Control",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "math"
    },
    {
        "id": "math.PR",
        "archive": "math",
        "subject_class": "PR",
        "definitive": true,
        "active": true,
        "category_name": "Probability",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "math"
    },
    {
        "id": "math.QA",
        "archive": "math",
        "subject_class": "QA",
        "definitive": true,
        "active": true,
        "category_name": "Quantum Algebra",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "math"
    },
    {
        "id": "math.RA",
        "archive": "math",
        "subject_class": "RA",
        "definitive": true,
        "active": true,
        "category_name": "Rings and Algebras",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "math"
    },
    {
        "id": "math.RT",
        "archive": "math",
        "subject_class": "RT",
        "definitive": true,
        "active": true,
        "category_name": "Representation Theory",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "math"
    },
    {
        "id": "math.SG",
        "archive": "math",
        "subject_class": "SG",
        "definitive": true,
        "active": true,
        "category_name": "Symplectic Geometry",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "math"
    },
    {
        "id": "math.SP",
        "archive": "math",
        "subject_class": "SP",
        "definitive": true,
        "active": true,
        "category_name": "Spectral Theory",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "math"
    },
    {
        "id": "math.ST",
        "archive": "math",
        "subject_class": "ST",
        "definitive": true,
        "active": true,
        "category_name": "Statistics Theory",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "math"
    },
    {
        "id": "math-ph.",
        "archive": "math-ph",
        "subject_class": "",
        "definitive": true,
        "active": true,
        "category_name": "Mathematical Physics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "math-ph"
    },
    {
        "id": "mtrl-th.",
        "archive": "mtrl-th",
        "subject_class": "",
        "definitive": true,
        "active": false,
        "category_name": "Materials Theory",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "mtrl-th"
    },
    {
        "id": "nlin.",
        "archive": "nlin",
        "subject_class": "",
        "definitive": false,
        "active": true,
        "category_name": "Nonlinear Sciences",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "nlin"
    },
    {
        "id": "nlin.AO",
        "archive": "nlin",
        "subject_class": "AO",
        "definitive": true,
        "active": true,
        "category_name": "Adaptation and Self-Organizing Systems",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "nlin"
    },
    {
        "id": "nlin.CD",
        "archive": "nlin",
        "subject_class": "CD",
        "definitive": true,
        "active": true,
        "category_name": "Chaotic Dynamics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "nlin"
    },
    {
        "id": "nlin.CG",
        "archive": "nlin",
        "subject_class": "CG",
        "definitive": true,
        "active": true,
        "category_name": "Cellular Automata and Lattice Gases",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "nlin"
    },
    {
        "id": "nlin.PS",
        "archive": "nlin",
        "subject_class": "PS",
        "definitive": true,
        "active": true,
        "category_name": "Pattern Formation and Solitons",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "nlin"
    },
    {
        "id": "nlin.SI",
        "archive": "nlin",
        "subject_class": "SI",
        "definitive": true,
        "active": true,
        "category_name": "Exactly Solvable and Integrable Systems",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "nlin"
    },
    {
        "id": "nucl-ex.",
        "archive": "nucl-ex",
        "subject_class": "",
        "definitive": true,
        "active": true,
        "category_name": "Nuclear Experiment",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "nucl-ex"
    },
    {
        "id": "nucl-th.",
        "archive": "nucl-th",
        "subject_class": "",
        "definitive": true,
        "active": true,
        "category_name": "Nuclear Theory",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "nucl-th"
    },
    {
        "id": "patt-sol.",
        "archive": "patt-sol",
        "subject_class": "",
        "definitive": true,
        "active": false,
        "category_name": "Pattern Formation and Solitons",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "patt-sol"
    },
    {
        "id": "physics.",
        "archive": "physics",
        "subject_class": "",
        "definitive": false,
        "active": true,
        "category_name": "Physics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "physics"
    },
    {
        "id": "physics.acc-ph",
        "archive": "physics",
        "subject_class": "acc-ph",
        "definitive": true,
        "active": true,
        "category_name": "Accelerator Physics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "physics.acc-ph"
    },
    {
        "id": "physics.ao-ph",
        "archive": "physics",
        "subject_class": "ao-ph",
        "definitive": true,
        "active": true,
        "category_name": "Atmospheric and Oceanic Physics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "physics.ao-ph"
    },
    {
        "id": "physics.app-ph",
        "archive": "physics",
        "subject_class": "app-ph",
        "definitive": true,
        "active": true,
        "category_name": "Applied Physics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "physics"
    },
    {
        "id": "physics.atm-clus",
        "archive": "physics",
        "subject_class": "atm-clus",
        "definitive": true,
        "active": true,
        "category_name": "Atomic and Molecular Clusters",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "physics.atm-clus"
    },
    {
        "id": "physics.atom-ph",
        "archive": "physics",
        "subject_class": "atom-ph",
        "definitive": true,
        "active": true,
        "category_name": "Atomic Physics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "physics.atom-ph"
    },
    {
        "id": "physics.bio-ph",
        "archive": "physics",
        "subject_class": "bio-ph",
        "definitive": true,
        "active": true,
        "category_name": "Biological Physics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "physics.bio-ph"
    },
    {
        "id": "physics.chem-ph",
        "archive": "physics",
        "subject_class": "chem-ph",
        "definitive": true,
        "active": true,
        "category_name": "Chemical Physics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "physics.chem-ph"
    },
    {
        "id": "physics.class-ph",
        "archive": "physics",
        "subject_class": "class-ph",
        "definitive": true,
        "active": true,
        "category_name": "Classical Physics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "physics.class-ph"
    },
    {
        "id": "physics.comp-ph",
        "archive": "physics",
        "subject_class": "comp-ph",
        "definitive": true,
        "active": true,
        "category_name": "Computational Physics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "physics.comp-ph"
    },
    {
        "id": "physics.data-an",
        "archive": "physics",
        "subject_class": "data-an",
        "definitive": true,
        "active": true,
        "category_name": "Data Analysis, Statistics and Probability",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "physics.data-an"
    },
    {
        "id": "physics.ed-ph",
        "archive": "physics",
        "subject_class": "ed-ph",
        "definitive": true,
        "active": true,
        "category_name": "Physics Education",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "physics.ed-ph"
    },
    {
        "id": "physics.flu-dyn",
        "archive": "physics",
        "subject_class": "flu-dyn",
        "definitive": true,
        "active": true,
        "category_name": "Fluid Dynamics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "physics.flu-dyn"
    },
    {
        "id": "physics.gen-ph",
        "archive": "physics",
        "subject_class": "gen-ph",
        "definitive": true,
        "active": true,
        "category_name": "General Physics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "physics.gen-ph"
    },
    {
        "id": "physics.geo-ph",
        "archive": "physics",
        "subject_class": "geo-ph",
        "definitive": true,
        "active": true,
        "category_name": "Geophysics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "physics.geo-ph"
    },
    {
        "id": "physics.hist-ph",
        "archive": "physics",
        "subject_class": "hist-ph",
        "definitive": true,
        "active": true,
        "category_name": "History and Philosophy of Physics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "physics.hist-ph"
    },
    {
        "id": "physics.ins-det",
        "archive": "physics",
        "subject_class": "ins-det",
        "definitive": true,
        "active": true,
        "category_name": "Instrumentation and Detectors",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "physics.ins-det"
    },
    {
        "id": "physics.med-ph",
        "archive": "physics",
        "subject_class": "med-ph",
        "definitive": true,
        "active": true,
        "category_name": "Medical Physics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "physics.med-ph"
    },
    {
        "id": "physics.optics",
        "archive": "physics",
        "subject_class": "optics",
        "definitive": true,
        "active": true,
        "category_name": "Optics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "physics.optics"
    },
    {
        "id": "physics.plasm-ph",
        "archive": "physics",
        "subject_class": "plasm-ph",
        "definitive": true,
        "active": true,
        "category_name": "Plasma Physics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "physics.plasm-ph"
    },
    {
        "id": "physics.pop-ph",
        "archive": "physics",
        "subject_class": "pop-ph",
        "definitive": true,
        "active": true,
        "category_name": "Popular Physics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "physics.pop-ph"
    },
    {
        "id": "physics.soc-ph",
        "archive": "physics",
        "subject_class": "soc-ph",
        "definitive": true,
        "active": true,
        "category_name": "Physics and Society",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "physics.soc-ph"
    },
    {
        "id": "physics.space-ph",
        "archive": "physics",
        "subject_class": "space-ph",
        "definitive": true,
        "active": true,
        "category_name": "Space Physics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "physics.space-ph"
    },
    {
        "id": "plasm-ph.",
        "archive": "plasm-ph",
        "subject_class": "",
        "definitive": true,
        "active": false,
        "category_name": "Plasma Physics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "plasm-ph"
    },
    {
        "id": "q-alg.",
        "archive": "q-alg",
        "subject_class": "",
        "definitive": true,
        "active": false,
        "category_name": "Quantum Algebra and Topology",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "q-alg"
    },
    {
        "id": "q-bio.",
        "archive": "q-bio",
        "subject_class": "",
        "definitive": false,
        "active": true,
        "category_name": "Quantitative Biology",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "q-bio"
    },
    {
        "id": "q-bio.BM",
        "archive": "q-bio",
        "subject_class": "BM",
        "definitive": true,
        "active": true,
        "category_name": "Biomolecules",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "q-bio"
    },
    {
        "id": "q-bio.CB",
        "archive": "q-bio",
        "subject_class": "CB",
        "definitive": true,
        "active": true,
        "category_name": "Cell Behavior",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "q-bio"
    },
    {
        "id": "q-bio.GN",
        "archive": "q-bio",
        "subject_class": "GN",
        "definitive": true,
        "active": true,
        "category_name": "Genomics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "q-bio"
    },
    {
        "id": "q-bio.MN",
        "archive": "q-bio",
        "subject_class": "MN",
        "definitive": true,
        "active": true,
        "category_name": "Molecular Networks",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "q-bio"
    },
    {
        "id": "q-bio.NC",
        "archive": "q-bio",
        "subject_class": "NC",
        "definitive": true,
        "active": true,
        "category_name": "Neurons and Cognition",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "q-bio"
    },
    {
        "id": "q-bio.OT",
        "archive": "q-bio",
        "subject_class": "OT",
        "definitive": true,
        "active": true,
        "category_name": "Other Quantitative Biology",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "q-bio"
    },
    {
        "id": "q-bio.PE",
        "archive": "q-bio",
        "subject_class": "PE",
        "definitive": true,
        "active": true,
        "category_name": "Populations and Evolution",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "q-bio"
    },
    {
        "id": "q-bio.QM",
        "archive": "q-bio",
        "subject_class": "QM",
        "definitive": true,
        "active": true,
        "category_name": "Quantitative Methods",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "q-bio"
    },
    {
        "id": "q-bio.SC",
        "archive": "q-bio",
        "subject_class": "SC",
        "definitive": true,
        "active": true,
        "category_name": "Subcellular Processes",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "q-bio"
    },
    {
        "id": "q-bio.TO",
        "archive": "q-bio",
        "subject_class": "TO",
        "definitive": true,
        "active": true,
        "category_name": "Tissues and Organs",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "q-bio"
    },
    {
        "id": "q-fin.",
        "archive": "q-fin",
        "subject_class": "",
        "definitive": false,
        "active": true,
        "category_name": "Quantitative Finance",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "q-fin"
    },
    {
        "id": "q-fin.CP",
        "archive": "q-fin",
        "subject_class": "CP",
        "definitive": true,
        "active": true,
        "category_name": "Computational Finance",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "q-fin"
    },
    {
        "id": "q-fin.EC",
        "archive": "q-fin",
        "subject_class": "EC",
        "definitive": true,
        "active": true,
        "category_name": "Economics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "q-fin"
    },
    {
        "id": "q-fin.GN",
        "archive": "q-fin",
        "subject_class": "GN",
        "definitive": true,
        "active": true,
        "category_name": "General Finance",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "q-fin"
    },
    {
        "id": "q-fin.MF",
        "archive": "q-fin",
        "subject_class": "MF",
        "definitive": true,
        "active": true,
        "category_name": "Mathematical Finance",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "q-fin"
    },
    {
        "id": "q-fin.PM",
        "archive": "q-fin",
        "subject_class": "PM",
        "definitive": true,
        "active": true,
        "category_name": "Portfolio Management",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "q-fin"
    },
    {
        "id": "q-fin.PR",
        "archive": "q-fin",
        "subject_class": "PR",
        "definitive": true,
        "active": true,
        "category_name": "Pricing of Securities",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "q-fin"
    },
    {
        "id": "q-fin.RM",
        "archive": "q-fin",
        "subject_class": "RM",
        "definitive": true,
        "active": true,
        "category_name": "Risk Management",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "q-fin"
    },
    {
        "id": "q-fin.ST",
        "archive": "q-fin",
        "subject_class": "ST",
        "definitive": true,
        "active": true,
        "category_name": "Statistical Finance",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "q-fin"
    },
    {
        "id": "q-fin.TR",
        "archive": "q-fin",
        "subject_class": "TR",
        "definitive": true,
        "active": true,
        "category_name": "Trading and Market Microstructure",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "q-fin"
    },
    {
        "id": "quant-ph.",
        "archive": "quant-ph",
        "subject_class": "",
        "definitive": true,
        "active": true,
        "category_name": "Quantum Physics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "quant-ph"
    },
    {
        "id": "solv-int.",
        "archive": "solv-int",
        "subject_class": "",
        "definitive": true,
        "active": false,
        "category_name": "Exactly Solvable and Integrable Systems",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "solv-int"
    },
    {
        "id": "stat.",
        "archive": "stat",
        "subject_class": "",
        "definitive": false,
        "active": true,
        "category_name": "Statistics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "stat"
    },
    {
        "id": "stat.AP",
        "archive": "stat",
        "subject_class": "AP",
        "definitive": true,
        "active": true,
        "category_name": "Applications",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "stat"
    },
    {
        "id": "stat.CO",
        "archive": "stat",
        "subject_class": "CO",
        "definitive": true,
        "active": true,
        "category_name": "Computation",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "stat"
    },
    {
        "id": "stat.ME",
        "archive": "stat",
        "subject_class": "ME",
        "definitive": true,
        "active": true,
        "category_name": "Methodology",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "stat"
    },
    {
        "id": "stat.ML",
        "archive": "stat",
        "subject_class": "ML",
        "definitive": true,
        "active": true,
        "category_name": "Machine Learning",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "stat"
    },
    {
        "id": "stat.OT",
        "archive": "stat",
        "subject_class": "OT",
        "definitive": true,
        "active": true,
        "category_name": "Other Statistics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "stat"
    },
    {
        "id": "stat.TH",
        "archive": "stat",
        "subject_class": "TH",
        "definitive": true,
        "active": true,
        "category_name": "Statistics Theory",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "stat"
    },
    {
        "id": "supr-con.",
        "archive": "supr-con",
        "subject_class": "",
        "definitive": true,
        "active": false,
        "category_name": "Superconductivity",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "supr-con"
    },
    {
        "id": "test.",
        "archive": "test",
        "subject_class": "",
        "definitive": false,
        "active": true,
        "category_name": "Test",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "test"
    },
    {
        "id": "test.dis-nn",
        "archive": "test",
        "subject_class": "dis-nn",
        "definitive": true,
        "active": true,
        "category_name": "Test Disruptive Networks",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "test"
    },
    {
        "id": "test.mes-hall",
        "archive": "test",
        "subject_class": "mes-hall",
        "definitive": true,
        "active": true,
        "category_name": "Test Hall",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "test"
    },
    {
        "id": "test.mtrl-sci",
        "archive": "test",
        "subject_class": "mtrl-sci",
        "definitive": true,
        "active": true,
        "category_name": "Test Mtrl-Sci",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "test"
    },
    {
        "id": "test.none",
        "archive": "test",
        "subject_class": "none",
        "definitive": true,
        "active": true,
        "category_name": "",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "test"
    },
    {
        "id": "test.soft",
        "archive": "test",
        "subject_class": "soft",
        "definitive": true,
        "active": true,
        "category_name": "Test Soft",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "test"
    },
    {
        "id": "test.stat-mech",
        "archive": "test",
        "subject_class": "stat-mech",
        "definitive": true,
        "active": true,
        "category_name": "Test Mechanics",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "test"
    },
    {
        "id": "test.str-el",
        "archive": "test",
        "subject_class": "str-el",
        "definitive": true,
        "active": true,
        "category_name": "Test Electrons",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "test"
    },
    {
        "id": "test.supr-con",
        "archive": "test",
        "subject_class": "supr-con",
        "definitive": true,
        "active": true,
        "category_name": "Test Superconductivity",
        "endorse_all": "d",
        "endorse_email": "d",
        "papers_to_endorse": 0,
        "endorsement_domain": "test"
    }
]

export default arxivCategories;