# Pipeline for CIT
kind: pipeline
type: exec
name: CIT Build

node:
  labels:
    environment:web40

steps:
  - name: test
    commands:
      - echo "Hello on VM"

---
kind: pipeline
type: kubernetes
name: build

node:
  labels:
    environment:gcp

environment:
  ARTIFACT_REPO: arxiv-keycloak

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: docker-socket
    path: /var/run
  - name: docker-cache
    path: /var/lib/docker


steps:
  - name: hello
    image: alpine
    commands:
      - set
    volumes:
      - name: docker-socket
        path: /var/run
    when:
      changeset:
        includes:
          - cicd/docker

# This build only succeeds after you bootstrap the arxiv-builder container
# You can do so by `make builder` in cicd/docker
  # - name: build
  #   image: gcr.io/arxiv-stage/arxiv-devops/arxiv-builder:e7a4be9
  #   privileged: true
  #   environment:
  #     GIT_SHA: ${DRONE_COMMIT_SHA}
  #     PLUGIN_JSON_KEY:
  #       from_secret: drone_runner_sa_key
  #   volumes:
  #     - name: docker-socket
  #       path: /var/run
  #   commands:
  #     - python3 /arxiv/setup_sa.py
  #     - . ./envvars && python3 /arxiv/docker_builder.py arxiv-keycloak keycloak_bend/ --repo $DRONE_REPO_NAME --gitsha $GIT_SHA -f keycloak_bend/Dockerfile
  #   depends_on:
  #     - hello

  # - name: failure
  #   image: gcr.io/arxiv-stage/arxiv-devops/arxiv-builder:e7a4be9
  #   privileged: true
  #   environment:
  #     SLACK_WEBHOOK_URL:
  #       from_secret: slack_webhook
  #   commands:
  #     - python3 /arxiv/slacker.py
  #   depends_on:
  #     - build
  #   when:
  #     status:
  #       - failure

  # - name: success
  #   image: gcr.io/arxiv-stage/arxiv-devops/arxiv-builder:e7a4be9
  #   privileged: true
  #   settings:
  #     slack_webhook_url:
  #       from_secret: slack_webhook
  #   commands:
  #     - echo SUCCESS

  #   depends_on:
  #     - build
  #   when:
  #     status:
  #       - success

volumes:
  - name: docker-cache
    persistentVolumeClaim:
      claimName: docker-cache-pvc
  - name: docker-socket
    host:
      path: /var/run

trigger:
  event:
    - push
