kind: pipeline
type: kubernetes
name: build-docker-images

node:
  environment: gcp

environment:
  ARTIFACT_REPO: arxiv-keycloak

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: docker-socket
    path: /var/run
  - name: docker-cache
    path: /var/lib/docker


steps:

  - name: hello
    image: alpine/git
    environment:
      GIT_SHA: ${DRONE_COMMIT_SHA}
      PLUGIN_JSON_KEY:
        from_secret: drone_runner_sa_key
    commands:
      - set
      - echo FOO=bar >> envvars
      - ls
      - git fetch origin $DRONE_COMMIT_BEFORE
      - echo "Comparing $DRONE_COMMIT_BEFORE → $DRONE_COMMIT_SHA"
      - git diff --name-only $DRONE_COMMIT_BEFORE $DRONE_COMMIT_SHA > changed_files.txt
      - cat changed_files.txt
      - grep -q '^keycloak_bend/' changed_files.txt && touch /tmp/run-keycloak_bend || echo "No changes in keycloak_bend"
      - grep -q '^account-ui/' changed_files.txt && touch /tmp/run-account-ui || echo "No changes in account-ui"
      - grep -q '^keycloak_tapir_bridge/' changed_files.txt && touch /tmp/run-keycloak_tapir_bridge || echo "No changes in keycloak_tapir_bridge"
      - grep -q '^oauth2-authenticator/' changed_files.txt && touch /tmp/run-oauth2-authenticator || echo "No changes in oauth2-authenticator"
      - grep -q '^user-portal/' changed_files.txt && touch /tmp/run-user-portal || echo "No changes in user-portal"
      - grep -q '^test-mta/' changed_files.txt && touch /tmp/run-test-mta || echo "No changes in test-mta"
    volumes:
      - name: docker-socket
        path: /var/run

  # Step: keycloak_bend
  - name: build-keycloak-bend
    image: gcr.io/arxiv-stage/arxiv-devops/arxiv-builder:1575e2fe2c54556229df469ed4cc237bc9ce130f
    privileged: true
    environment:
      GIT_SHA: ${DRONE_COMMIT_SHA}
      PLUGIN_JSON_KEY:
        from_secret: drone_runner_sa_key
    volumes:
      - name: docker-socket
        path: /var/run
    commands:
      - python3 /arxiv/setup_sa.py
      -  if [ -f /tmp/run-keycloak_bend ]; then . ./envvars && python3 /arxiv/docker_builder.py arxiv-keycloak keycloak_bend/ --repo $DRONE_REPO_NAME --gitsha $GIT_SHA -f keycloak_bend/Dockerfile; fi
    depends_on:
      - hello

  # Step: account-ui
  - name: build-account-ui
    image: gcr.io/arxiv-stage/arxiv-devops/arxiv-builder:1575e2fe2c54556229df469ed4cc237bc9ce130f
    privileged: true
    environment:
      GIT_SHA: ${DRONE_COMMIT_SHA}
      PLUGIN_JSON_KEY:
        from_secret: drone_runner_sa_key
    volumes:
      - name: docker-socket
        path: /var/run
    commands:
      - python3 /arxiv/setup_sa.py
      - if [ -f /tmp/run-account-ui ]; then . ./envvars && python3 /arxiv/docker_builder.py account-ui account-ui/account-app/ --repo $DRONE_REPO_NAME --gitsha $GIT_SHA -f account-ui/account-app/Dockerfile ; fi
    depends_on:
      - hello
      
  # Step: keycloak_tapir_bridge
  - name: build-keycloak-tapir-bridge
    image: gcr.io/arxiv-stage/arxiv-devops/arxiv-builder:1575e2fe2c54556229df469ed4cc237bc9ce130f
    privileged: true
    environment:
      GIT_SHA: ${DRONE_COMMIT_SHA}
      PLUGIN_JSON_KEY:
        from_secret: drone_runner_sa_key
    volumes:
      - name: docker-socket
        path: /var/run
    commands:
      - python3 /arxiv/setup_sa.py
      - if [ -f /tmp/run-keycloak_tapir_bridge ]; then . ./envvars && python3 /arxiv/docker_builder.py keycloak-tapir-bridge keycloak_tapir_bridge/ --repo $DRONE_REPO_NAME --gitsha $GIT_SHA -f keycloak_tapir_bridge/Dockerfile; fi
    depends_on:
      - hello

  # Step: oauth2-authenticator
  - name: build-oauth2-authenticator
    image: gcr.io/arxiv-stage/arxiv-devops/arxiv-builder:1575e2fe2c54556229df469ed4cc237bc9ce130f
    privileged: true
    environment:
      GIT_SHA: ${DRONE_COMMIT_SHA}
      PLUGIN_JSON_KEY:
        from_secret: drone_runner_sa_key
    volumes:
      - name: docker-socket
        path: /var/run
    commands:
      - python3 /arxiv/setup_sa.py
      - if [ -f /tmp/run-oauth2-authenticator ]; then . ./envvars && python3 /arxiv/docker_builder.py oauth2-authenticator oauth2-authenticator/ --repo $DRONE_REPO_NAME --gitsha $GIT_SHA -f oauth2-authenticator/Dockerfile ; fi
    depends_on:
      - hello

  # Step: test-mta
  - name: build-test-mta
    image: gcr.io/arxiv-stage/arxiv-devops/arxiv-builder:1575e2fe2c54556229df469ed4cc237bc9ce130f
    privileged: true
    environment:
      GIT_SHA: ${DRONE_COMMIT_SHA}
      PLUGIN_JSON_KEY:
        from_secret: drone_runner_sa_key
    volumes:
      - name: docker-socket
        path: /var/run
    commands:
      - python3 /arxiv/setup_sa.py
      - if [ -f /tmp/run-test-mta ]; then . ./envvars && python3 /arxiv/docker_builder.py test-mta test-mta/ --repo $DRONE_REPO_NAME --gitsha $GIT_SHA -f test-mta/Dockerfile ; fi
      - if [ -f /tmp/run-test-mta ]; then . ./envvars && python3 /arxiv/docker_builder.py email-to-pubsub test-mta/ --repo $DRONE_REPO_NAME --gitsha $GIT_SHA -f test-mta/email-to-pubsub.Dockerfile ; fi
    depends_on:
      - hello

  # Step: user-portal
  - name: build-user-portal
    image: gcr.io/arxiv-stage/arxiv-devops/arxiv-builder:1575e2fe2c54556229df469ed4cc237bc9ce130f
    privileged: true
    environment:
      GIT_SHA: ${DRONE_COMMIT_SHA}
      PLUGIN_JSON_KEY:
        from_secret: drone_runner_sa_key
    volumes:
      - name: docker-socket
        path: /var/run
    commands:
      - python3 /arxiv/setup_sa.py
      - if [ -f /tmp/run-user-portal ]; then . ./envvars && python3 /arxiv/docker_builder.py user-portal user-portal/ --repo $DRONE_REPO_NAME --gitsha $GIT_SHA -f user-portal/Dockerfile ; fi
    depends_on:
      - hello

  - name: failure
    image: gcr.io/arxiv-stage/arxiv-devops/arxiv-builder:e7a4be9
    privileged: true
    environment:
      SLACK_WEBHOOK_URL:
        from_secret: slack_webhook
    commands:
      # - python3 /arxiv/slacker.py
      - echo bummer
    when:
      status:
        - failure
    depends_on:
      - build-keycloak-bend
      - build-account-ui
      - build-keycloak-tapir-bridge
      - build-oauth2-authenticator
      - build-test-mta
      - build-user-portal

  - name: success
    image: gcr.io/arxiv-stage/arxiv-devops/arxiv-builder:e7a4be9
    privileged: true
    settings:
      slack_webhook_url:
        from_secret: slack_webhook
    commands:
      - echo SUCCESS
    depends_on:
      - build-keycloak-bend
      - build-account-ui
      - build-keycloak-tapir-bridge
      - build-oauth2-authenticator
      - build-test-mta
      - build-user-portal
    when:
      status:
        - success

volumes:
  - name: docker-cache
    persistentVolumeClaim:
      claimName: docker-cache-pvc
  - name: docker-socket
    host:
      path: /var/run

trigger:
  event:
    - push
---
# Pipeline for CentOS 9
kind: pipeline
type: exec
name: centos-9-deploy

node:
  environment: centos9
depends_on:
  - build-docker-images

platform:
  os: linux
  arch: amd64

steps:
  - name: refresh dockers
    commands:
      - whoami
      - export HOME=/home/drone
      - export GOOGLE_APPLICATION_CREDENTIALS=/opt_arxiv/bomb-range/cred/drone-runner-sa.json
      - gcloud auth activate-service-account --key-file=/opt_arxiv/bomb-range/cred/drone-runner-sa.json
      - gcloud auth configure-docker gcr.io
      - cd /opt_arxiv/bomb-range
      - make down
      - make up
