class Encoder:
    def __init__(self): ...
    def set_bit_rate(self, bitrate: int) -> None: ...
    def encode(self, pcm_data: bytes) -> bytes: ...
    def set_in_sample_rate(self, rate: float) -> None: ...
    def set_channels(self, channels: int) -> None: ...
    def set_quality(self, quality: float) -> None: ...
    def flush(self) -> bytes: ...
