- pipeline.id: mysql-submissions
  path.config: "/usr/share/logstash/pipeline/mysql-submissions.conf"
  pipeline.workers: 4
  pipeline.batch.size: 5000

- pipeline.id: rest-api-submissions
  path.config: "/usr/share/logstash/pipeline/rest-api-submissions.conf"
  pipeline.workers: 2
  pipeline.batch.size: 1000

- pipeline.id: pubsub-submissions
  path.config: "/usr/share/logstash/pipeline/pubsub-submissions.conf"
  pipeline.workers: 4
  pipeline.batch.size: 1000
