[tool.poetry]
name = "keycloak-bend"
version = "0.1.0"
description = "Keycloak Backend Development Tools"
authors = ["developers@arxiv.org"]
license = "BSD-3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
python-keycloak = "^5.1.1"
arxiv-base = {git = "https://github.com/arXiv/arxiv-base.git", rev = "develop"}


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
selenium = "^4.27.1"
types-requests = "^2.32.0.20241016"
python-dotenv = "^1.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
