// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: 953436a8360641634556fba4ed0ee4305b24809a887cd5d480b0afa4c64c6b2a

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "kc-arXiv-react";

export const themeNames: ThemeName[] = ["kc-arXiv-react"];

export type KcEnvName =
    | "ARXIV_USER_REGISTRATION_URL"
    | "ARXIV_PRIVACY_POLICY"
    | "ARXIV_MEMBER_INSTITUTIONS";

export const kcEnvNames: KcEnvName[] = [
    "ARXIV_USER_REGISTRATION_URL",
    "ARXIV_PRIVACY_POLICY",
    "ARXIV_MEMBER_INSTITUTIONS"
];

export const kcEnvDefaults: Record<KcEnvName, string> = {
    ARXIV_USER_REGISTRATION_URL: "https://arxiv.org/user/register",
    ARXIV_PRIVACY_POLICY: "https://arxiv.org/help/policies/privacy_policy",
    ARXIV_MEMBER_INSTITUTIONS: "https://info.arxiv.org/about/ourmembers.html"
};

/**
 * NOTE: Do not import this type except maybe in your entrypoint.
 * If you need to import the KcContext import it either from src/login/KcContext.ts or src/account/KcContext.ts.
 * Depending on the theme type you are working on.
 */
export type KcContext = import("./login/KcContext").KcContext;

declare global {
    interface Window {
        kcContext?: KcContext;
    }
}

export const KcLoginPage = lazy(() => import("./login/KcPage"));

export function KcPage(props: { kcContext: KcContext; fallback?: ReactNode }) {
    const { kcContext, fallback } = props;
    return (
        <Suspense fallback={fallback}>
            {(() => {
                switch (kcContext.themeType) {
                    case "login":
                        return <KcLoginPage kcContext={kcContext} />;
                }
            })()}
        </Suspense>
    );
}
