// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: addd2415021434aee08592925d9a0b9d749baf18870bff2328cc7ff5e00a92bb

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "kc-arXiv-react";

export const themeNames: ThemeName[] = ["kc-arXiv-react"];

export type KcEnvName =
    | "ARXIV_USER_LOGIN_URL"
    | "ARXIV_USER_REGISTRATION_URL"
    | "ARXIV_PRIVACY_POLICY"
    | "ARXIV_MEMBER_INSTITUTIONS";

export const kcEnvNames: KcEnvName[] = [
    "ARXIV_USER_LOGIN_URL",
    "ARXIV_USER_REGISTRATION_URL",
    "ARXIV_PRIVACY_POLICY",
    "ARXIV_MEMBER_INSTITUTIONS"
];

export const kcEnvDefaults: Record<KcEnvName, string> = {
    ARXIV_USER_LOGIN_URL: "https://arxiv.org/login",
    ARXIV_USER_REGISTRATION_URL: "https://arxiv.org/user-account/register",
    ARXIV_PRIVACY_POLICY: "https://arxiv.org/help/policies/privacy_policy",
    ARXIV_MEMBER_INSTITUTIONS: "https://info.arxiv.org/about/ourmembers.html"
};

/**
 * NOTE: Do not import this type except maybe in your entrypoint.
 * If you need to import the KcContext import it either from src/login/KcContext.ts or src/account/KcContext.ts.
 * Depending on the theme type you are working on.
 */
export type KcContext =
    | import("./login/KcContext").KcContext
    | import("./account/KcContext").KcContext;

declare global {
    interface Window {
        kcContext?: KcContext;
    }
}

export const KcLoginPage = lazy(() => import("./login/KcPage"));
export const KcAccountPage = lazy(() => import("./account/KcPage"));

export function KcPage(props: { kcContext: KcContext; fallback?: ReactNode }) {
    const { kcContext, fallback } = props;
    return (
        <Suspense fallback={fallback}>
            {(() => {
                switch (kcContext.themeType) {
                    case "login":
                        return <KcLoginPage kcContext={kcContext} />;
                    case "account":
                        return <KcAccountPage kcContext={kcContext} />;
                }
            })()}
        </Suspense>
    );
}
