options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IMAGE_NAME: "keycloak"
  _DOCKERFILE: "Dockerfile"
  
steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-f"
      - "${_DOCKERFILE}"
      - "-t"
      - "gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA"
      - "-t"
      - "gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest"
      - "keycloak_bend"
    id: Build

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - "--all-tags"
      - "gcr.io/$PROJECT_ID/${_IMAGE_NAME}"

images:
  [
    "gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest",
    "gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA",
  ]
  
