#!/bin/sh
SQL_FILE=$1
shift
echo mysql -h $MYSQL_HOST -P $MYSQL_TCP_PORT -u root -p$MYSQL_ROOT_PASSWORD $MYSQL_DATABASE  from $SQL_FILE
mysql -h $MYSQL_HOST -P $MYSQL_TCP_PORT -u root -p$MYSQL_ROOT_PASSWORD $MYSQL_DATABASE < $SQL_FILE
