/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Login
         * @description User can log in with username and password, or permanent token.
         */
        get: operations["login_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Oauth2 Callback
         * @description User can log in with username and password, or permanent token.
         */
        get: operations["oauth2_callback_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Refresh Token
         * @description Refresh the access token
         *
         *     current_user: Optional[ArxivUserClaims] = Depends(get_current_user_or_none)
         *     is the standard method of getting the cookie/user but since this is a refresh request, it is likely
         *     the user claims expired, and thus no "current user".
         *
         *     IOW, this needs to get to the refresh token, turn it into access token and recreate the cookie if
         *     it succeeds.
         *
         *     The code here mirrors to get_current_user_or_none, so maybe I should refactor to do the first part of
         *     checking the cookies and rehydrate it.
         */
        get: operations["refresh_token_refresh_get"];
        put?: never;
        /** Refresh Tokens */
        post: operations["refresh_tokens_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Logout
         * @description Log out of arXiv.
         */
        get: operations["logout_logout_get"];
        put?: never;
        /**
         * Logout
         * @description Log out of arXiv.
         */
        post: operations["logout_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logout-callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_logout_callback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/token-names": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Token Names */
        get: operations["get_token_names_token_names_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/check-db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check Db */
        get: operations["check_db_check_db_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/info/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Info
         * @description Hit the db and get user info
         */
        get: operations["info_account_info_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/info/id:str": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Info
         * @description Hit the db and get user info
         */
        get: operations["info_account_info_id_str_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Register */
        get: operations["get_register_account_register__get"];
        put?: never;
        /**
         * Register
         * @description Create a new user
         */
        post: operations["register_account_register__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/email/verify/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Email Verify Requset */
        post: operations["email_verify_requset_account_email_verify__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/countries/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Countries */
        get: operations["list_countries_countries__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/countries/alpha_2/{alpha_2}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Country */
        get: operations["get_country_countries_alpha_2__alpha_2__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/captcha/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Captcha Image */
        get: operations["get_captcha_image_captcha_image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/captcha/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Captcha Token */
        get: operations["get_captcha_token_captcha_token_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_categories__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{archive}/subject-class": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Subject Classes */
        get: operations["list_subject_classes_categories__archive__subject_class_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{archive}/subject-class/{subject_class}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Category */
        get: operations["get_category_categories__archive__subject_class__subject_class__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Category */
        get: operations["get_category_categories__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_documents__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/paper_id/{paper_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document
         * @description Display a paper.
         */
        get: operations["get_document_documents_paper_id__paper_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document
         * @description Display a paper.
         */
        get: operations["get_document_documents__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Submissions */
        get: operations["list_submissions_submissions__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/paper/{paper_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Submission By Paper Id
         * @description Display a paper.
         */
        get: operations["get_submission_by_paper_id_submissions_paper__paper_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Submission
         * @description Display a paper.
         */
        get: operations["get_submission_submissions__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/document/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Submission By Document Id
         * @description Display a paper.
         */
        get: operations["get_submission_by_document_id_submissions_document__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/paper_owners/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ownerships */
        get: operations["list_ownerships_paper_owners__get"];
        put?: never;
        /** Create Ownership */
        post: operations["create_ownership_paper_owners__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/paper_owners/user/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ownerships For User */
        get: operations["list_ownerships_for_user_paper_owners_user__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/paper_owners/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ownership */
        get: operations["get_ownership_paper_owners__id__get"];
        /** Update Ownership */
        put: operations["update_ownership_paper_owners__id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/states": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_states_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountInfoModel */
        AccountInfoModel: {
            /** Username */
            username: string;
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Suffix Name */
            suffix_name: string | null;
            /** Country */
            country: string | null;
            /** Affiliation */
            affiliation: string | null;
            default_category: components["schemas"]["CategoryIdModel"] | null;
            /** Groups */
            groups: string[] | null;
            /** Url */
            url: string | null;
            /** Joined Date */
            joined_date: number | null;
            /** Oidc Id */
            oidc_id: string | null;
            /** Career Status */
            career_status: string;
            /** Id */
            id: string;
            /** Email Verified */
            email_verified: boolean;
            /** Scopes */
            scopes: string[] | null;
        };
        /** AccountRegistrationModel */
        AccountRegistrationModel: {
            /** Username */
            username: string;
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Suffix Name */
            suffix_name: string | null;
            /** Country */
            country: string | null;
            /** Affiliation */
            affiliation: string | null;
            default_category: components["schemas"]["CategoryIdModel"] | null;
            /** Groups */
            groups: string[] | null;
            /** Url */
            url: string | null;
            /** Joined Date */
            joined_date: number | null;
            /** Oidc Id */
            oidc_id: string | null;
            /** Career Status */
            career_status: string;
            /** Password */
            password: string;
            /** Origin Ip */
            origin_ip: string | null;
            /** Origin Host */
            origin_host: string | null;
            /** Token */
            token: string;
            /** Captcha Value */
            captcha_value: string;
            /**
             * Keycloak Migration
             * @default false
             */
            keycloak_migration: boolean;
        };
        /** CaptchaTokenReplyModel */
        CaptchaTokenReplyModel: {
            /** Token */
            token: string;
        };
        /** CategoryIdModel */
        CategoryIdModel: {
            /** Archive */
            archive: string;
            /** Subject Class */
            subject_class: string;
        };
        /** CategoryModel */
        CategoryModel: {
            /** Id */
            id: string;
            /** Archive */
            archive: string;
            /** Subject Class */
            subject_class: string | null;
            /** Definitive */
            definitive: boolean;
            /** Active */
            active: boolean;
            /** Category Name */
            category_name: string | null;
            /** Endorse All */
            endorse_all: string;
            /** Endorse Email */
            endorse_email: string;
            /** Papers To Endorse */
            papers_to_endorse: number;
            /** Endorsement Domain */
            endorsement_domain: string | null;
        };
        /** CountryModel */
        CountryModel: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Numeric Id */
            numeric_id: string;
            /** Official Name */
            official_name: string;
        };
        /** DocumentModel */
        DocumentModel: {
            /** Id */
            id: number;
            /** Paper Id */
            paper_id: string;
            /** Title */
            title: string;
            /** Authors */
            authors: string | null;
            /** Submitter Email */
            submitter_email: string;
            /** Submitter Id */
            submitter_id: number | null;
            /**
             * Dated
             * Format: date-time
             */
            dated: string;
            /** Primary Subject Class */
            primary_subject_class: string | null;
            /** Created */
            created: string | null;
            /** Last Submission Id */
            last_submission_id: number | null;
        };
        /** EmailModel */
        EmailModel: {
            /** Email */
            email: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** OwnershipModel */
        OwnershipModel: {
            /** Id */
            id: string;
            /** Document Id */
            document_id: number;
            /** User Id */
            user_id: number;
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /** Added By */
            added_by: number;
            /** Remote Addr */
            remote_addr: string;
            /** Remote Host */
            remote_host: string;
            /** Tracking Cookie */
            tracking_cookie: string;
            /** Valid */
            valid: boolean;
            /** Flag Author */
            flag_author: boolean;
            /** Flag Auto */
            flag_auto: boolean;
        };
        /**
         * RefreshedTokens
         * @description Token refresh reply
         */
        RefreshedTokens: {
            /** Session */
            session: string;
            /** Classic */
            classic: string | null;
            /** Domain */
            domain: string | null;
            /** Max Age */
            max_age: number;
            /** Secure */
            secure: boolean;
            /** Samesite */
            samesite: string;
        };
        /** SubmissionCategoryModel */
        SubmissionCategoryModel: {
            /** Category */
            category: string;
            /** Is Primary */
            is_primary: boolean;
            /** Is Published */
            is_published: boolean | null;
        };
        /** SubmissionModel */
        SubmissionModel: {
            /** Id */
            id: number;
            /** Document Id */
            document_id: number | null;
            /** Doc Paper Id */
            doc_paper_id: string | null;
            /** Sword Id */
            sword_id: number | null;
            /** Userinfo */
            userinfo: number | null;
            /** Is Author */
            is_author: number;
            /** Agree Policy */
            agree_policy: number | null;
            /** Viewed */
            viewed: number | null;
            /** Stage */
            stage: number | null;
            /** Submitter Id */
            submitter_id: number | null;
            /** Submitter Name */
            submitter_name: string | null;
            /** Submitter Email */
            submitter_email: string | null;
            /** Created */
            created: string | null;
            /** Updated */
            updated: string | null;
            /** Status */
            status: number;
            /** Sticky Status */
            sticky_status: number | null;
            /** Must Process */
            must_process: number | null;
            /** Submit Time */
            submit_time: string | null;
            /** Release Time */
            release_time: string | null;
            /** Source Size */
            source_size: number | null;
            /** Source Format */
            source_format: string | null;
            /** Source Flags */
            source_flags: string | null;
            /** Has Pilot Data */
            has_pilot_data: number | null;
            /** Is Withdrawn */
            is_withdrawn: number;
            /** Title */
            title: string | null;
            /** Authors */
            authors: string | null;
            /** Comments */
            comments: string | null;
            /** Proxy */
            proxy: string | null;
            /** Report Num */
            report_num: string | null;
            /** Msc Class */
            msc_class: string | null;
            /** Acm Class */
            acm_class: string | null;
            /** Journal Ref */
            journal_ref: string | null;
            /** Doi */
            doi: string | null;
            /** Abstract */
            abstract: string | null;
            /** License */
            license: string | null;
            /** Version */
            version: number;
            /** Type */
            type: string | null;
            /** Is Ok */
            is_ok: number | null;
            /** Admin Ok */
            admin_ok: number | null;
            /** Allow Tex Produced */
            allow_tex_produced: number | null;
            /** Is Oversize */
            is_oversize: number | null;
            /** Remote Addr */
            remote_addr: string;
            /** Remote Host */
            remote_host: string;
            /** Package */
            package: string;
            /** Rt Ticket Id */
            rt_ticket_id: number | null;
            /** Auto Hold */
            auto_hold: number | null;
            /** Is Locked */
            is_locked: number;
            /** Agreement Id */
            agreement_id: number | null;
            /** Submission Categories */
            submission_categories: components["schemas"]["SubmissionCategoryModel"][] | null;
        };
        /**
         * Tokens
         * @description Token refresh request body
         */
        Tokens: {
            /** Classic */
            classic: string | null;
            /** Session */
            session: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    oauth2_callback_callback_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    refresh_token_refresh_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    refresh_tokens_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Tokens"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshedTokens"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_logout_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    logout_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    logout_logout_callback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_token_names_token_names_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    check_db_check_db_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    info_account_info_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountInfoModel"];
                };
            };
        };
    };
    info_account_info_id_str_get: {
        parameters: {
            query: {
                id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountInfoModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_register_account_register__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptchaTokenReplyModel"];
                };
            };
        };
    };
    register_account_register__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountRegistrationModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountInfoModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    email_verify_requset_account_email_verify__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_countries_countries__get: {
        parameters: {
            query?: {
                /** @description sort by */
                _sort?: string | null;
                /** @description sort order */
                _order?: string | null;
                _start?: number | null;
                _end?: number | null;
                name?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountryModel"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_country_countries_alpha_2__alpha_2__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alpha_2: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountryModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_captcha_image_captcha_image_get: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "image/png": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_captcha_token_captcha_token_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptchaTokenReplyModel"];
                };
            };
        };
    };
    list_categories_categories__get: {
        parameters: {
            query?: {
                /** @description sort order */
                _order?: string | null;
                _start?: number | null;
                _end?: number | null;
                archive?: string | null;
                subject_class?: string | null;
                /** @description active */
                active?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryModel"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_subject_classes_categories__archive__subject_class_get: {
        parameters: {
            query?: {
                /** @description sort order */
                _order?: string | null;
                _start?: number | null;
                _end?: number | null;
            };
            header?: never;
            path: {
                archive: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryModel"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_category_categories__archive__subject_class__subject_class__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                archive: string;
                subject_class: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_category_categories__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_documents__get: {
        parameters: {
            query?: {
                /** @description sort by */
                _sort?: string | null;
                /** @description sort order */
                _order?: string | null;
                _start?: number | null;
                _end?: number | null;
                /** @description List of document IDs to filter by */
                id?: number[] | null;
                preset?: string | null;
                /** @description Start date for filtering */
                start_date?: string | null;
                /** @description End date for filtering */
                end_date?: string | null;
                /** @description arXiv ID */
                paper_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentModel"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_documents_paper_id__paper_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_documents__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_submissions_submissions__get: {
        parameters: {
            query?: {
                /** @description sort by */
                _sort?: string | null;
                /** @description sort order */
                _order?: string | null;
                _start?: number | null;
                _end?: number | null;
                preset?: string | null;
                /** @description Start date for filtering */
                start_date?: string | null;
                /** @description End date for filtering */
                end_date?: string | null;
                /** @description Stage */
                stage?: number[] | null;
                /** @description Submission status */
                submission_status?: number[] | null;
                /** @description List of user IDs to filter by */
                id?: number[] | null;
                /** @description Document ID */
                document_id?: number | null;
                /** @description Submitter ID */
                submitter_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionModel"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_submission_by_paper_id_submissions_paper__paper_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_submission_submissions__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_submission_by_document_id_submissions_document__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ownerships_paper_owners__get: {
        parameters: {
            query?: {
                /** @description sort by */
                _sort?: string | null;
                /** @description sort order */
                _order?: string | null;
                _start?: number | null;
                _end?: number | null;
                preset?: string | null;
                /** @description Start date for filtering */
                start_date?: string | null;
                /** @description End date for filtering */
                end_date?: string | null;
                flag_valid?: boolean | null;
                user_id?: number | null;
                document_id?: number | null;
                /** @description List of paper owner */
                id?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnershipModel"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_ownership_paper_owners__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnershipModel"];
                };
            };
        };
    };
    list_ownerships_for_user_paper_owners_user__user_id__get: {
        parameters: {
            query?: {
                /** @description sort by */
                _sort?: string | null;
                /** @description sort order */
                _order?: string | null;
                _start?: number | null;
                _end?: number | null;
                preset?: string | null;
                /** @description Start date for filtering */
                start_date?: string | null;
                /** @description End date for filtering */
                end_date?: string | null;
                flag_valid?: boolean | null;
                document_id?: number | null;
            };
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnershipModel"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ownership_paper_owners__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnershipModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_ownership_paper_owners__id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnershipModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_states_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
}
