/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/countries/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Countries */
        get: operations["list_countries_v1_countries__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/countries/alpha_2/{alpha_2}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Country */
        get: operations["get_country_v1_countries_alpha_2__alpha_2__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_v1_categories__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/categories/{archive}/subject-class": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Subject Classes */
        get: operations["list_subject_classes_v1_categories__archive__subject_class_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/categories/{archive}/subject-class/{subject_class}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Category */
        get: operations["get_category_v1_categories__archive__subject_class__subject_class__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Category */
        get: operations["get_category_v1_categories__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_v1_documents__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/paper_id/{paper_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document
         * @description Display a paper.
         */
        get: operations["get_document_v1_documents_paper_id__paper_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document
         * @description Display a paper.
         */
        get: operations["get_document_v1_documents__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/submissions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Submissions */
        get: operations["list_submissions_v1_submissions__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/submissions/paper/{paper_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Submission By Paper Id
         * @description Display a paper.
         */
        get: operations["get_submission_by_paper_id_v1_submissions_paper__paper_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/submissions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Submission
         * @description Display a paper.
         */
        get: operations["get_submission_v1_submissions__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/submissions/document/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Submission By Document Id
         * @description Display a paper.
         */
        get: operations["get_submission_by_document_id_v1_submissions_document__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/paper_owners/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ownerships */
        get: operations["list_ownerships_v1_paper_owners__get"];
        put?: never;
        /** Create Ownership */
        post: operations["create_ownership_v1_paper_owners__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/paper_owners/user/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ownerships For User */
        get: operations["list_ownerships_for_user_v1_paper_owners_user__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/paper_owners/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ownership */
        get: operations["get_ownership_v1_paper_owners__id__get"];
        /** Update Ownership */
        put: operations["update_ownership_v1_paper_owners__id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/states": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_states_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CategoryModel */
        CategoryModel: {
            /** Id */
            id: string;
            /** Archive */
            archive: string;
            /** Subject Class */
            subject_class: string | null;
            /** Definitive */
            definitive: boolean;
            /** Active */
            active: boolean;
            /** Category Name */
            category_name: string | null;
            /** Endorse All */
            endorse_all: string;
            /** Endorse Email */
            endorse_email: string;
            /** Papers To Endorse */
            papers_to_endorse: number;
            /** Endorsement Domain */
            endorsement_domain: string | null;
        };
        /** CountryModel */
        CountryModel: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Numeric Id */
            numeric_id: string;
            /** Official Name */
            official_name: string;
        };
        /** DocumentModel */
        DocumentModel: {
            /** Id */
            id: number;
            /** Paper Id */
            paper_id: string;
            /** Title */
            title: string;
            /** Authors */
            authors?: string | null;
            /** Submitter Email */
            submitter_email: string;
            /** Submitter Id */
            submitter_id?: number | null;
            /**
             * Dated
             * Format: date-time
             */
            dated: string;
            /** Primary Subject Class */
            primary_subject_class?: string | null;
            /** Created */
            created?: string | null;
            /** Last Submission Id */
            last_submission_id?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** OwnershipModel */
        OwnershipModel: {
            /** Id */
            id: string;
            /** Document Id */
            document_id: number;
            /** User Id */
            user_id: number;
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /** Added By */
            added_by: number;
            /** Remote Addr */
            remote_addr: string;
            /** Remote Host */
            remote_host: string;
            /** Tracking Cookie */
            tracking_cookie: string;
            /** Valid */
            valid: boolean;
            /** Flag Author */
            flag_author: boolean;
            /** Flag Auto */
            flag_auto: boolean;
        };
        /** SubmissionCategoryModel */
        SubmissionCategoryModel: {
            /** Category */
            category: string;
            /** Is Primary */
            is_primary: boolean;
            /** Is Published */
            is_published: boolean | null;
        };
        /** SubmissionModel */
        SubmissionModel: {
            /** Id */
            id: number;
            /** Document Id */
            document_id: number | null;
            /** Doc Paper Id */
            doc_paper_id: string | null;
            /** Sword Id */
            sword_id: number | null;
            /** Userinfo */
            userinfo: number | null;
            /** Is Author */
            is_author: number;
            /** Agree Policy */
            agree_policy: number | null;
            /** Viewed */
            viewed: number | null;
            /** Stage */
            stage: number | null;
            /** Submitter Id */
            submitter_id: number | null;
            /** Submitter Name */
            submitter_name: string | null;
            /** Submitter Email */
            submitter_email: string | null;
            /** Created */
            created: string | null;
            /** Updated */
            updated: string | null;
            /** Status */
            status: number;
            /** Sticky Status */
            sticky_status: number | null;
            /** Must Process */
            must_process: number | null;
            /** Submit Time */
            submit_time: string | null;
            /** Release Time */
            release_time: string | null;
            /** Source Size */
            source_size: number | null;
            /** Source Format */
            source_format: string | null;
            /** Source Flags */
            source_flags: string | null;
            /** Has Pilot Data */
            has_pilot_data: number | null;
            /** Is Withdrawn */
            is_withdrawn: number;
            /** Title */
            title: string | null;
            /** Authors */
            authors: string | null;
            /** Comments */
            comments: string | null;
            /** Proxy */
            proxy: string | null;
            /** Report Num */
            report_num: string | null;
            /** Msc Class */
            msc_class: string | null;
            /** Acm Class */
            acm_class: string | null;
            /** Journal Ref */
            journal_ref: string | null;
            /** Doi */
            doi: string | null;
            /** Abstract */
            abstract: string | null;
            /** License */
            license: string | null;
            /** Version */
            version: number;
            /** Type */
            type: string | null;
            /** Is Ok */
            is_ok: number | null;
            /** Admin Ok */
            admin_ok: number | null;
            /** Allow Tex Produced */
            allow_tex_produced: number | null;
            /** Is Oversize */
            is_oversize: number | null;
            /** Remote Addr */
            remote_addr: string;
            /** Remote Host */
            remote_host: string;
            /** Package */
            package: string;
            /** Rt Ticket Id */
            rt_ticket_id: number | null;
            /** Auto Hold */
            auto_hold: number | null;
            /** Is Locked */
            is_locked: number;
            /** Agreement Id */
            agreement_id: number | null;
            /** Submission Categories */
            submission_categories: components["schemas"]["SubmissionCategoryModel"][] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_countries_v1_countries__get: {
        parameters: {
            query?: {
                /** @description sort by */
                _sort?: string | null;
                /** @description sort order */
                _order?: string | null;
                _start?: number | null;
                _end?: number | null;
                name?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountryModel"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_country_v1_countries_alpha_2__alpha_2__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alpha_2: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountryModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_categories_v1_categories__get: {
        parameters: {
            query?: {
                /** @description sort order */
                _order?: string | null;
                _start?: number | null;
                _end?: number | null;
                archive?: string | null;
                subject_class?: string | null;
                /** @description active */
                active?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryModel"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_subject_classes_v1_categories__archive__subject_class_get: {
        parameters: {
            query?: {
                /** @description sort order */
                _order?: string | null;
                _start?: number | null;
                _end?: number | null;
            };
            header?: never;
            path: {
                archive: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryModel"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_category_v1_categories__archive__subject_class__subject_class__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                archive: string;
                subject_class: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_category_v1_categories__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_v1_documents__get: {
        parameters: {
            query?: {
                /** @description sort by */
                _sort?: string | null;
                /** @description sort order */
                _order?: string | null;
                _start?: number | null;
                _end?: number | null;
                /** @description List of document IDs to filter by */
                id?: number[] | null;
                preset?: string | null;
                /** @description Start date for filtering */
                start_date?: string | null;
                /** @description End date for filtering */
                end_date?: string | null;
                /** @description arXiv ID */
                paper_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentModel"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_v1_documents_paper_id__paper_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_v1_documents__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_submissions_v1_submissions__get: {
        parameters: {
            query?: {
                /** @description sort by */
                _sort?: string | null;
                /** @description sort order */
                _order?: string | null;
                _start?: number | null;
                _end?: number | null;
                preset?: string | null;
                /** @description Start date for filtering */
                start_date?: string | null;
                /** @description End date for filtering */
                end_date?: string | null;
                /** @description Stage */
                stage?: number[] | null;
                /** @description Submission status */
                submission_status?: number[] | null;
                /** @description List of user IDs to filter by */
                id?: number[] | null;
                /** @description Document ID */
                document_id?: number | null;
                /** @description Submitter ID */
                submitter_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionModel"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_submission_by_paper_id_v1_submissions_paper__paper_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_submission_v1_submissions__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_submission_by_document_id_v1_submissions_document__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ownerships_v1_paper_owners__get: {
        parameters: {
            query?: {
                /** @description sort by */
                _sort?: string | null;
                /** @description sort order */
                _order?: string | null;
                _start?: number | null;
                _end?: number | null;
                preset?: string | null;
                /** @description Start date for filtering */
                start_date?: string | null;
                /** @description End date for filtering */
                end_date?: string | null;
                flag_valid?: boolean | null;
                user_id?: number | null;
                document_id?: number | null;
                /** @description List of paper owner */
                id?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnershipModel"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_ownership_v1_paper_owners__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnershipModel"];
                };
            };
        };
    };
    list_ownerships_for_user_v1_paper_owners_user__user_id__get: {
        parameters: {
            query?: {
                /** @description sort by */
                _sort?: string | null;
                /** @description sort order */
                _order?: string | null;
                _start?: number | null;
                _end?: number | null;
                preset?: string | null;
                /** @description Start date for filtering */
                start_date?: string | null;
                /** @description End date for filtering */
                end_date?: string | null;
                flag_valid?: boolean | null;
                document_id?: number | null;
            };
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnershipModel"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ownership_v1_paper_owners__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnershipModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_ownership_v1_paper_owners__id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnershipModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_states_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
}
